version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: cesar
      POSTGRES_PASSWORD: tu_password_seguro
      POSTGRES_DB: db_motos
    networks:
      - red_compartida
    volumes:
      - db_data_motos:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.hostname == Worker-1
      restart_policy:
        condition: on-failure

  web:
    image: cesartellez301/motos:latest
    ports:
      - "8009:5000"
    environment:
      DATABASE_URL: postgresql://cesar:tu_password_seguro@db:5432/db_motos
    networks:
      - red_compartida
      - red_publica
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure

networks:
  # Una sola red interna controlada por el Stack para evitar fallos de traducción de host
  red_compartida:
    driver: overlay
  red_publica:
    name: stack-motos_red_publica
    external: true

volumes:
  db_data_motos: